# Generated by Django 5.2.17 on 2026-09-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Artists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
