# Generated by Django 5.2.17 on 2026-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_track_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
