# Generated by Django 5.2.17 on 2026-09-14 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(related_name='tracks', to='music.genre'),
        ),
    ]
