# Generated by Django 5.2.17 on 2026-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_album_alter_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
