# Generated by Django 5.2.17 on 2026-09-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='App Stats', editable=False, max_length=100)),
                ('user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('song_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
