# Generated by Django 5.2.17 on 2026-09-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstat',
            name='genre_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
