# Generated by Django 5.2.17 on 2026-09-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appstat_genre_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstat',
            name='artist_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
