# Generated by Django 5.2.17 on 2026-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appstat_artist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstat',
            name='album_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
