# Generated by Django 5.2.17 on 2026-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
