# Generated by Django 5.2.17 on 2026-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visit_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='IP',
            new_name='ip',
        ),
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
