# Generated by Django 5.2.17 on 2026-09-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_ip_visit_ip_visit_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='browser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
