
# Generated by Django 5.2.17 on 2026-09-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
            ),
        ),
    ]

