# Generated by Django 5.2.17 on 2026-09-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_useractivity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
