# Generated by Django 5.2.17 on 2026-09-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_useractivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
