# Generated by Django 5.2.17 on 2026-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
