# Generated by Django 5.2.17 on 2026-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
