# Generated by Django 5.2.17 on 2026-09-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_featured'),
        ('music', '0008_album_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.track'),
            preserve_default=False,
        ),
    ]
