# Generated by Django 5.2.17 on 2026-09-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_track'),
        ('music', '0008_album_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.track'),
        ),
    ]
